### ISSUE TITLE
models and tables

### ISSUE THREAD

**Issue by larshollingsed** [larshollingsed/06-23-catering#13]
#### employees table

| id (primary key) | name (text) | age (integer) |
| --- | --- | --- |
| 1 | April | 33 |
| 2 | Jarad | 35 |
| 3 | Lars | 18 |
#### events table

| id (primary key) | date (text) | hours (number) | hourly_wage (number) | gratuity (number) | alcohol (text) |
| --- | --- | --- | --- | --- | --- |
| 1 | 06-11 | 5.5 | 10.50 | 30 | true |
| 2 | 06-12 | 7 | 9.75 | 50 | true |
| 3 | 06-13 | 4 | 15.00 | 0 | false |
#### distributions table

| id (primary key) | employee_id (foreign key) | event_id (foreign key) | manager (text) |
| --- | --- | --- | --- |
| 1 | 1 | 1 | true |
| 2 | 1 | 2 | false |
| 3 | 2 | 1 | false |
| 4 | 3 | 1 | false |

**Comment by sumeetjain** [comment]
- [x] The `?` for booleans is actually just a Ruby thing – you shouldn't name the column in the table with it.
- [x] Can't use spaces in table column names. (https://github.com/omahacodeschool/wiki/blob/master/ruby/naming-things.md)

Those are two quick fixes, after which :+1: :rocket:
